version: "3.8"

services:
  header-check-server:
    build: .
    ports:
      - "3000:3000"
    networks:
      - nginx-network

networks:
  nginx-network:
    external: true
    name: "nginx-network"